INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (100, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (200, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (300, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (200, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (100, 'Crise nas infinitas Terras', 100, 100, 10, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (200, 'Guerra Infinita', 100, 200, 15, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (300, 'Sharp Objects', 200, 300, 100, CURRENT_TIMESTAMP);
